<template>
  <div :id="id" :style="{'width':width,'height':height}"></div>
</template>
<script>
  import echarts from 'echarts'
  export default {
    data () {
      return {
        myChart:null,
        chartId: this.id
      }
    },
    props:{
      id:{
        type:String,
        default:'yourID'
      },
      width:{
        type:String,
        default:'300px'
      },
      height:{
        type:String,
        default:'300px'
      }
    },
    computed:{
      vipSetOption () {
        return {
          tooltip:{
            trigger:'axis',
            axisPointer:{
              type:'shadow'
            }
          },
          legend:{
            data:['直接访问','邮件营销','联盟广告','视频广告','搜索引擎']
          },
          grid:{
            left:'3%',
            right:'4%',
            bottom:'3%',
            containLabel:true
          },
          xAxis:{
            type:'value'
          },
          yAxis:{
            type:'category',
            data:['周一','周二','周三','周四','周五','周六','周日']
          },
          series:[
            {
              name:'直接访问',
              type:'bar',
              stack:'总量',
              label:{
                normal:{
                  show:true,
                  position:'insideRight'
                }
              },
              data:[320,302,301,334,390,330,320]
            },
            {
              name:'邮件营销',
              type:'bar',
              stack:'总量',
              label:{
                normal:{
                  show:true,
                  position:'insideRight'
                }
              },
              data:[320,302,301,334,390,330,320]
            },
            {
              name:'联盟广告',
              type:'bar',
              stack:'总量',
              label:{
                normal:{
                  show:true,
                  position:'insideRight'
                }
              },
              data:[320,302,301,334,390,330,320]
            },
            {
              name:'视频广告',
              type:'bar',
              stack:'总量',
              label:{
                normal:{
                  show:true,
                  position:'insideRight'
                }
              },
              data:[320,302,301,334,390,330,320]
            },
            {
              name:'搜索引擎',
              type:'bar',
              stack:'总量',
              label:{
                normal:{
                  show:true,
                  position:'insideRight'
                }
              },
              data:[320,302,301,334,390,330,320]
            }
          ],
        }
      }
    },
    mounted(){
      this.drawCompanyTotal();
      setTimeout(()=>{
        window.addEventListener('resize',()=>{
          this.vipSetOption.myChart.resize()
        })
      })
    },
    methods:{
      drawCompanyTotal(){
        this.myChart = this.$echarts.init(document.getElementById(this.chartId),'light')
        this.myChart.setOption(this.vipSetOption)
      },
    }
  }
</script>
<style scoped>
</style>
